# Generated by Django 5.1.2 on 2024-11-26 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINISTRACION', '0006_factura_detallefactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='estado_pago',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='fecha_emision',
        ),
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='factura',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='factura',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
    ]
