# Generated by Django 5.1.2 on 2024-11-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMINISTRACION', '0008_alter_factura_cliente_alter_factura_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='empleado',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
